//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using BLToolkit.Data;
using BLToolkit.Data.Linq;
using BLToolkit.DataAccess;
using BLToolkit.Mapping;

namespace DataModel
{
	public partial class OstarDB : DbManager
    {
        public OstarDB()
            : base(new BLToolkit.Data.DataProvider.MySqlDataProvider(), System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString)
        {
        }
        public Table<certificado> certificado { get { return this.GetTable<certificado>(); } }
        public Table<domicilio> domicilio { get { return this.GetTable<domicilio>(); } }
        public Table<emisor> emisor { get { return this.GetTable<emisor>(); } }
        public Table<factura> factura { get { return this.GetTable<factura>(); } }
        public Table<proveedor> proveedor { get { return this.GetTable<proveedor>(); } }
        public Table<receptor> receptor { get { return this.GetTable<receptor>(); } }
        public Table<roles> roles { get { return this.GetTable<roles>(); } }
        public Table<ticket> ticket { get { return this.GetTable<ticket>(); } }
        public Table<ticket_detalle> ticket_detalle { get { return this.GetTable<ticket_detalle>(); } }
        public Table<userclaims> userclaims { get { return this.GetTable<userclaims>(); } }
        public Table<userlogins> userlogins { get { return this.GetTable<userlogins>(); } }
        public Table<userroles> userroles { get { return this.GetTable<userroles>(); } }
        public Table<users> users { get { return this.GetTable<users>(); } }
        public Table<useremisor> useremisor { get { return this.GetTable<useremisor>(); } }
        public Table<config> config { get { return this.GetTable<config>(); } }
        public Table<servisim> servisim { get { return this.GetTable<servisim>(); } }

        public Table<producto> producto { get { return this.GetTable<producto>(); } }
        public Table<folio> folio { get { return this.GetTable<folio>(); } }
        public Table<moneda> moneda { get { return this.GetTable<moneda>(); } }
        public Table<pago> pago { get { return this.GetTable<pago>(); } }
        public Table<tipo> tipo { get { return this.GetTable<tipo>(); } }

        public Table<ticket_retencion> ticket_retencion { get { return this.GetTable<ticket_retencion>(); } }
        public Table<ticket_traslado> ticket_traslado { get { return this.GetTable<ticket_traslado>(); } }
        public Table<ticket_retencion_local> ticket_retencion_local { get { return this.GetTable<ticket_retencion_local>(); } }
        public Table<ticket_traslado_local> ticket_traslado_local { get { return this.GetTable<ticket_traslado_local>(); } }

        //tablas para CFDI 3.3
        public Table<cRegimenFiscal> cRegimenFiscal { get { return this.GetTable<cRegimenFiscal>(); } }
        public Table<cClaveProdServ> cClaveProdServ { get { return this.GetTable<cClaveProdServ>(); } }
        public Table<emisor_cProdServ> emisor_cProdServ { get { return this.GetTable<emisor_cProdServ>(); } }
        public Table<cMetodoPago> cMetodoPago { get { return this.GetTable<cMetodoPago>(); } }
        public Table<cPais> cPais { get { return this.GetTable<cPais>(); } }
        public Table<cClaveUnidad> cClaveUnidad { get { return this.GetTable<cClaveUnidad>(); } }
        public Table<cUsoCFDI> cUsoCFDI { get { return this.GetTable<cUsoCFDI>(); } }
        public Table<cFormaPago> cFormaPago { get { return this.GetTable<cFormaPago>(); } }
        public Table<cTipoFactor> cTipoFactor { get { return this.GetTable<cTipoFactor>(); } }
        public Table<cTasaOCuota> cTasaOCuota { get { return this.GetTable<cTasaOCuota>(); } }

        public Table<cTipoRelacion> cTipoRelacion { get { return this.GetTable<cTipoRelacion>(); } }
        //estas tabla fueron agregadas el 10/09/2015 para el CFDIRIP
        public Table<cfdirip> cfdirip { get { return this.GetTable<cfdirip>(); } }
        public Table<impuestosretenidos> impuestosretenidos { get { return this.GetTable<impuestosretenidos>(); } }

        public Table<arrendamientoenfideicomiso> arrendamientoenfideicomiso { get { return this.GetTable<arrendamientoenfideicomiso>(); } }
        public Table<dividendos> dividendos { get { return this.GetTable<dividendos>(); } }
        public Table<enajenaciondeacciones> enajenaciondeacciones { get { return this.GetTable<enajenaciondeacciones>(); } }
        public Table<fideicnoempresarial> fideicnoempresarial { get { return this.GetTable<fideicnoempresarial>(); } }
        public Table<intereses> intereses { get { return this.GetTable<intereses>(); } }
        public Table<intereseshipotecarios> intereseshipotecarios { get { return this.GetTable<intereseshipotecarios>(); } }
        public Table<operacionesconderivados> operacionesconderivados { get { return this.GetTable<operacionesconderivados>(); } }
        public Table<pagosaextranjeros> pagosaextranjeros { get { return this.GetTable<pagosaextranjeros>(); } }
        public Table<planesderetiro> planesderetiro { get { return this.GetTable<planesderetiro>(); } }
        public Table<premios> premios { get { return this.GetTable<premios>(); } }
        public Table<sectorfinanciero> sectorfinanciero { get { return this.GetTable<sectorfinanciero>(); } }

        public Table<catalogopaises> catalogopaises { get { return this.GetTable<catalogopaises>(); } }
        public Table<facturacfdirip> facturacfdirip { get { return this.GetTable<facturacfdirip>(); } }
    }

    [TableName(Name = "certificado")]
    public partial class certificado
    {
        [Identity, PrimaryKey(1)]
        public int idcertificado { get; set; } // int(10)
        public string llave_privada { get; set; } // varchar(60)
        public string contrasenia { get; set; } // varchar(30)
        public string csd { get; set; } // varchar(60)

        // fk_emisor_certificado_BackReference
        [Association(ThisKey = "idcertificado", OtherKey = "cetificado", CanBeNull = true)]
        public IEnumerable<emisor> fkemisors { get; set; }
    }

    [TableName(Name = "domicilio")]
    public partial class domicilio
    {
        [Identity, PrimaryKey(1)]
        public int iddomicilio { get; set; } // int(10)
        [Nullable]
        public string calle { get; set; } // varchar(60)
        [Nullable]
        public string no_exterior { get; set; } // varchar(30)
        [Nullable]
        public string no_interior { get; set; } // varchar(30)
        [Nullable]
        public string colonia { get; set; } // varchar(45)
        [Nullable]
        public string municipio { get; set; } // varchar(60)
        [Nullable]
        public string localidad { get; set; } // varchar(60)
        [Nullable]
        public string referencia { get; set; } // varchar(60)
        [Nullable]
        public string estado { get; set; } // varchar(60)
        public string pais { get; set; } // varchar(30)
        [Nullable]
        public string codigo_postal { get; set; } // varchar(5)

        // fk_emisor_domicilio_BackReference
        [Association(ThisKey = "iddomicilio", OtherKey = "domicilio", CanBeNull = true)]
        public IEnumerable<emisor> fkemisors { get; set; }

        // fk_receptor_domicilio_BackReference
        [Association(ThisKey = "iddomicilio", OtherKey = "domicilio", CanBeNull = true)]
        public IEnumerable<receptor> fkreceptors { get; set; }

        // fk_emisor_sucursal_BackReference
        [Association(ThisKey = "iddomicilio", OtherKey = "sucursal", CanBeNull = true)]
        public IEnumerable<emisor> fkemisors2 { get; set; }
    }

    [TableName(Name = "emisor")]
    public partial class emisor
    {
        [Identity, PrimaryKey(1)]
        public int idemisor { get; set; } // int(10)
        public string identificador { get; set; } // varchar(13)
        public string rfc { get; set; } // varchar(13)
        public string razon_social { get; set; } // varchar(100)
        [Nullable]
        public string curp { get; set; }//varchar(18)
        [Nullable]
        public string logotipo { get; set; } // varchar(50)
        [Nullable]
        public string cedula { get; set; } // varchar(50)
        [Nullable]
        public Guid? cRegimenFiscal_id { get; set; } // varchar(100)
        public string lugar_expedicion { get; set; }
        //public int domicilio { get; set; } // int(10)
        public int cetificado { get; set; } // int(10)
        [Nullable]
        public int? sucursal { get; set; } // int(10)
        [Nullable]
        public int? tipo_pdf { get; set; } // int(10)

        // fk_emisor_certificado
        [Association(ThisKey = "cetificado", OtherKey = "idcertificado", CanBeNull = false)]
        public certificado fkcertificado { get; set; }

        //// fk_emisor_domicilio
        //[Association(ThisKey = "domicilio", OtherKey = "iddomicilio", CanBeNull = false)]
        //public domicilio fkdomicilio { get; set; }

        // fk_emisor_sucursal
        [Association(ThisKey = "sucursal", OtherKey = "iddomicilio", CanBeNull = true)]
        public domicilio fksucursal { get; set; }

        // fk_emisor_regimen
        [Association(ThisKey = "cRegimenFiscal_id", OtherKey = "cRegimenFiscal_id", CanBeNull = true)]
        public cRegimenFiscal fkregimen { get; set; }

        // fk_ticket_emisor_BackReference
        [Association(ThisKey = "idemisor", OtherKey = "emisor", CanBeNull = true)]
        public IEnumerable<ticket> fktickets { get; set; }

        // fk_folio_emisor_BackReference
        [Association(ThisKey = "idemisor", OtherKey = "emisor", CanBeNull = true)]
        public IEnumerable<folio> fkfolios { get; set; }

        // fk_producto_emisor_BackReference
        [Association(ThisKey = "idemisor", OtherKey = "emisor", CanBeNull = true)]
        public IEnumerable<producto> fkproductos { get; set; }

        // fk_cfdirip_emisor_BackReference
        [Association(ThisKey = "idemisor", OtherKey = "emisor", CanBeNull = true)]
        public IEnumerable<emisor_cProdServ> fkemisor_cProdServ { get; set; }

        //referencias a CFDIRIP
        // fk_emisor_cProdServ_BackReference
        [Association(ThisKey = "idemisor", OtherKey = "emisor", CanBeNull = true)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "factura")]
    public partial class factura
    {
        [PrimaryKey(1)]
        public string uuid { get; set; } // char(36)
        public DateTime fecha_timbrado { get; set; } // datetime
        public int receptor { get; set; } // int(10)
        public int ticket { get; set; } // int(10)

        // fk_factura_receptor
        [Association(ThisKey = "receptor", OtherKey = "idreceptor", CanBeNull = false)]
        public receptor fkreceptor { get; set; }

        // fk_factura_ticket
        [Association(ThisKey = "ticket", OtherKey = "idticket", CanBeNull = false)]
        public ticket fkticket { get; set; }
    }

    [TableName(Name = "proveedor")]
    public partial class proveedor
    {
        [Identity, PrimaryKey(1)]
        public int idproveedor { get; set; } // int(10)
        public string rfc { get; set; } // varchar(13)
        public string razon_social { get; set; } // varchar(60)
        public string correo_electronico { get; set; } // varchar(60)
        [Nullable]
        public string contacto { get; set; } // varchar(60)
        [Nullable]
        public string telefono { get; set; } // varchar(20)
        [PrimaryKey(2)]
        public string UserId { get; set; } // varchar(45)

        // fk_comprobante_proveedor_BackReference
        [Association(ThisKey = "idproveedor", OtherKey = "proveedor", CanBeNull = true)]
        public IEnumerable<factura> fkfcaturas { get; set; }
    }

    [TableName(Name = "receptor")]
    public partial class receptor
    {
        [Identity, PrimaryKey(1)]
        public int idreceptor { get; set; } // int(10)
        public string identificador { get; set; } // varchar(13)
        public string rfc { get; set; } // varchar(13)
        public string razon_social { get; set; } // varchar(60)
        public int? domicilio { get; set; } // int(10)
        public int emisor { get; set; } // int(10)
        public string nacionalidad { get; set; }//Varchar(10)
        public string curp { get; set; }//varchar(18)
        [Nullable]
        public string numregidtrib { get; set; }//varchar(20)
        [Nullable]
        // fk_receptor_domicilio
        [Association(ThisKey = "domicilio", OtherKey = "iddomicilio", CanBeNull = false)]
        public domicilio fkdomicilio { get; set; }

        // fk_factura_receptor_BackReference
        [Association(ThisKey = "idreceptor", OtherKey = "receptor", CanBeNull = true)]
        public IEnumerable<factura> fkfacturas { get; set; }

        // fk_facturacfdirip_receptor_BackReference
        [Association(ThisKey = "idreceptor", OtherKey = "receptor", CanBeNull = true)]
        public IEnumerable<facturacfdirip> fkfacturascfdirip { get; set; }

        // fk_cfdirip_receptor_BackReference
        [Association(ThisKey = "idreceptor", OtherKey = "receptor", CanBeNull = true)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }

    }

    [TableName(Name = "roles")]
    public partial class roles
    {
        [PrimaryKey(1)]
        public string Id { get; set; } // varchar(45)
        [Nullable]
        public string Name { get; set; } // varchar(45)

        // userroles_ibfk_2_BackReference
        [Association(ThisKey = "Id", OtherKey = "RoleId", CanBeNull = true)]
        public IEnumerable<userroles> userrolesibfk2s { get; set; }
    }

    [TableName(Name = "ticket")]
    public partial class ticket
    {
        [Identity, PrimaryKey(1)]
        public int idticket { get; set; } // int(10)
        public string metodo_pago { get; set; } // varchar(30)
        [Nullable]
        public string cuenta_pago { get; set; } // varchar(20)
        public string forma_pago { get; set; } // varchar(35)
        public decimal subtotal { get; set; } // decimal(18,6)
        public decimal tasa_iva { get; set; } // decimal(10,6)
        public decimal iva { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? tipo_cambio { get; set; } // decimal(10,6)
        [Nullable]
        public string moneda { get; set; } // varchar(10)
        [Nullable]
        public decimal? descuento { get; set; } // decimal(10,6)
        [Nullable]
        public string motivo_decuento { get; set; } // varchar(60)
        public decimal total { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? tasa_ieps { get; set; } // decimal(10,6)
        [Nullable]
        public decimal? ieps { get; set; } // decimal(18,6)
        [Nullable]
        public DateTime? fecha { get; set; } // datetime
        [Nullable]
        public string condiciones_pago { get; set; } // varchar(60)
        public string tipo_comprobante { get; set; } // varchar(60)
        [Nullable]
        public int? tipo_documento { get; set; } // varchar(60)
        public string serie { get; set; } // varchar(60)
        public int folio { get; set; } // varchar(60)
        [Nullable]
        public string origen { get; set; } // varchar(60)
        [Nullable]
        public string contrato { get; set; } // varchar(60)
        [Nullable]
        public DateTime? fecha_pago { get; set; } // datetime
        public int emisor { get; set; } // int(10)
        public int receptor { get; set; } // int(10)
        public string rfc_emisor { get; set; } // int(10)
        public string rfc_receptor { get; set; } // int(10)
        public string identificador { get; set; } // int(10)
        public string estatus { get; set; } // int(10)
        public string residencia_fiscal { get; set; } // int(10)
        public string uso_cfdi { get; set; } // int(10)
        public string tipo_relacion { get; set; } // int(10)
        public string cfdi_relacionado { get; set; } // int(10)

        // fk_ticket_emisor
        [Association(ThisKey = "emisor", OtherKey = "idemisor", CanBeNull = false)]
        public emisor fkemisor { get; set; }

        // fk_factura_ticket_BackReference
        [Association(ThisKey = "idticket", OtherKey = "ticket", CanBeNull = true)]
        public IEnumerable<factura> fkfacturas { get; set; }

        // fk_ticket_detalle_BackReference
        [Association(ThisKey = "idticket", OtherKey = "ticket", CanBeNull = true)]
        public IEnumerable<ticket_detalle> fkdetalles { get; set; }

        // fk_ticket_detalle_BackReference
        [Association(ThisKey = "idticket", OtherKey = "ticket", CanBeNull = true)]
        public IEnumerable<ticket_traslado> fktraslados { get; set; }

        // fk_ticket_detalle_BackReference
        [Association(ThisKey = "idticket", OtherKey = "ticket", CanBeNull = true)]
        public IEnumerable<ticket_retencion> fkretenciones { get; set; }

        // fk_ticket_detalle_BackReference
        [Association(ThisKey = "idticket", OtherKey = "ticket", CanBeNull = true)]
        public IEnumerable<ticket_traslado_local> fktrasladoslocales { get; set; }

        // fk_ticket_detalle_BackReference
        [Association(ThisKey = "idticket", OtherKey = "ticket", CanBeNull = true)]
        public IEnumerable<ticket_retencion_local> fkretencioneslocales { get; set; }
    }

    [TableName(Name = "ticket_detalle")]
    public partial class ticket_detalle
    {
        [Identity, PrimaryKey(1)]
        public int idticket_detalle { get; set; } // int(10)
        public decimal cantidad { get; set; } // decimal(18,6)
        public string unidad { get; set; } // varchar(25)
        public string clave_unidad { get; set; } // varchar(45)
        [Nullable]
        public string no_identificacion { get; set; } // varchar(25)
        public string clave_prod_serv { get; set; } // varchar(45)
        public string descripcion { get; set; } // varchar(150)
        public decimal valor_unitario { get; set; } // decimal(18,6)
        public decimal importe { get; set; } // decimal(18,6)
        [Nullable]
        public string cuenta_predial { get; set; } // varchar(25)
        [Nullable]
        public decimal? descuento { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? iva { get; set; } // decimal(18,6)
        [Nullable]
        public string tipo_factor_iva { get; set; } // varchar(150)
        [Nullable]
        public decimal? iva_ret { get; set; } // decimal(18,6)
        [Nullable]
        public string tipo_factor_iva_ret { get; set; } // varchar(150)
        [Nullable]
        public decimal? isr_ret { get; set; } // decimal(18,6)
        [Nullable]
        public string tipo_factor_isr_ret { get; set; } // varchar(150)
        [Nullable]
        public decimal? ieps { get; set; } // decimal(18,6)
        [Nullable]
        public string tipo_factor_ieps { get; set; } // varchar(150)
        [Nullable]
        public decimal? ish { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? isn { get; set; } // decimal(18,6)
        [Nullable]
        public DateTime? fecha_pago { get; set; } // datetime
        [Nullable]
        public decimal? tipo_cambio { get; set; } // decimal(18,6)
        public int ticket { get; set; } // int(10)

        // fk_ticket_detalle
        [Association(ThisKey = "ticket", OtherKey = "idticket", CanBeNull = false)]
        public ticket fkticketdetalle { get; set; }
    }

    [TableName(Name = "ticket_retencion")]
    public partial class ticket_retencion
    {
        [Identity, PrimaryKey(1)]
        public int idticket_retencion { get; set; } // int(10)
        public string impuesto { get; set; } // varchar(25)
        public decimal tasa { get; set; } // decimal(18,6)
        public decimal importe { get; set; } // decimal(18,6)
        public decimal base_impuesto { get; set; } // decimal(18,6)
        public string tipo_factor { get; set; } // varchar(25)
        public int ticket { get; set; } // int(10)

        // fk_ticket_detalle
        [Association(ThisKey = "ticket", OtherKey = "idticket", CanBeNull = false)]
        public ticket fkticketretencion { get; set; }
    }

    [TableName(Name = "ticket_traslado")]
    public partial class ticket_traslado
    {
        [Identity, PrimaryKey(1)]
        public int idticket_traslado { get; set; } // int(10)
        public string impuesto { get; set; } // varchar(25)
        public decimal tasa { get; set; } // decimal(18,6)
        public decimal importe { get; set; } // decimal(18,6)
        public decimal base_impuesto { get; set; } // decimal(18,6)
        public string tipo_factor { get; set; } // varchar(25)
        public int ticket { get; set; } // int(10)

        // fk_ticket_detalle
        [Association(ThisKey = "ticket", OtherKey = "idticket", CanBeNull = false)]
        public ticket fktickettraslado { get; set; }
    }

    [TableName(Name = "ticket_retencion_local")]
    public partial class ticket_retencion_local
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int(10)
        public string impuesto { get; set; } // varchar(25)
        public decimal tasa { get; set; } // decimal(18,6)
        public decimal importe { get; set; } // decimal(18,6)
        public int ticket { get; set; } // int(10)

        // fk_ticket_detalle
        [Association(ThisKey = "ticket", OtherKey = "idticket", CanBeNull = false)]
        public ticket fkticketretencionlocal { get; set; }
    }

    [TableName(Name = "ticket_traslado_local")]
    public partial class ticket_traslado_local
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int(10)
        public string impuesto { get; set; } // varchar(25)
        public decimal tasa { get; set; } // decimal(18,6)
        public decimal importe { get; set; } // decimal(18,6)
        public int ticket { get; set; } // int(10)

        // fk_ticket_detalle
        [Association(ThisKey = "ticket", OtherKey = "idticket", CanBeNull = false)]
        public ticket fktickettrasladolocal { get; set; }
    }

    [TableName(Name = "userclaims")]
    public partial class userclaims
    {
        [Identity, PrimaryKey(1)]
        public int Id { get; set; } // int(10)
        [Nullable]
        public string UserId { get; set; } // varchar(45)
        [Nullable]
        public string ClaimType { get; set; } // varchar(100)
        [Nullable]
        public string ClaimValue { get; set; } // varchar(100)

        // userclaims_ibfk_1
        [Association(ThisKey = "UserId", OtherKey = "Id", CanBeNull = true)]
        public users ibfk1 { get; set; }
    }

    [TableName(Name = "userlogins")]
    public partial class userlogins
    {
        public string UserId { get; set; } // varchar(45)
        [Nullable]
        public string ProviderKey { get; set; } // varchar(100)
        [Nullable]
        public string LoginProvider { get; set; } // varchar(100)

        // userlogins_ibfk_1
        [Association(ThisKey = "UserId", OtherKey = "Id", CanBeNull = false)]
        public users ibfk1 { get; set; }
    }

    [TableName(Name = "userroles")]
    public partial class userroles
    {
        [PrimaryKey(1)]
        public string UserId { get; set; } // varchar(45)
        [PrimaryKey(2)]
        public string RoleId { get; set; } // varchar(45)

        // userroles_ibfk_1
        [Association(ThisKey = "UserId", OtherKey = "Id", CanBeNull = false)]
        public users ibfk1 { get; set; }

        // userroles_ibfk_2
        [Association(ThisKey = "RoleId", OtherKey = "Id", CanBeNull = false)]
        public roles ibfk2 { get; set; }
    }

    [TableName(Name = "users")]
    public partial class users
    {
        [PrimaryKey(1)]
        public string Id { get; set; } // varchar(45)
        [Nullable]
        public string UserName { get; set; } // varchar(45)
        [Nullable]
        public string PasswordHash { get; set; } // varchar(100)
        [Nullable]
        public string SecurityStamp { get; set; } // varchar(45)
        [Nullable]
        public string Email { get; set; } // varchar(100)
        [Nullable]
        public string Phone { get; set; } // varchar(45)

        // userclaims_ibfk_1_BackReference
        [Association(ThisKey = "Id", OtherKey = "UserId", CanBeNull = true)]
        public IEnumerable<userclaims> userclaimsibfk1s { get; set; }

        // userlogins_ibfk_1_BackReference
        [Association(ThisKey = "Id", OtherKey = "UserId", CanBeNull = true)]
        public IEnumerable<userlogins> userloginsibfk1s { get; set; }

        // userroles_ibfk_1_BackReference
        [Association(ThisKey = "Id", OtherKey = "UserId", CanBeNull = true)]
        public IEnumerable<userroles> userrolesibfk1s { get; set; }
    }

    [TableName(Name = "config")]
    public partial class config
    {
        public string aplicacion { get; set; } // varchar(45)
        [Nullable]
        public string licencia { get; set; } // varchar(45)
        [Nullable]
        public string servidor { get; set; } // varchar(45)
        [Nullable]
        public int puerto { get; set; } // varchar(45)
        [Nullable]
        public int? ssl { get; set; } // varchar(45)
        [Nullable]
        public string nombre { get; set; } // varchar(45)
        [Nullable]
        public string correo { get; set; } // varchar(45)
        [Nullable]
        public string contrasenia { get; set; } // varchar(45)
        [Nullable]
        public string mensaje { get; set; } // text
    }

    [TableName(Name = "useremisor")]
    public partial class useremisor
    {
        [PrimaryKey(1)]
        public string UserId { get; set; } // varchar(45)
        [PrimaryKey(2)]
        public int EmisorId { get; set; } // varchar(45)

        // userroles_ibfk_1
        [Association(ThisKey = "UserId", OtherKey = "Id", CanBeNull = false)]
        public users ibfk1 { get; set; }

        // userroles_ibfk_2
        [Association(ThisKey = "EmisorId", OtherKey = "idemisor", CanBeNull = false)]
        public emisor ibfk2 { get; set; }
    }

    [TableName(Name = "servisim")]
    public partial class servisim
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int(10)
        [Nullable]
        public string usuario { get; set; } // varchar(45)
        [Nullable]
        public string contrasenia { get; set; } // varchar(100)
        [Nullable]
        public string token { get; set; } // varchar(150)
    }

    [TableName(Name = "folio")]
    public partial class folio
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int
        public string serie { get; set; } // varchar(20)
        [Nullable]
        public int folio_inicio { get; set; } // int(11)
        [Nullable]
        public int folio_actual { get; set; } // int(11)
        public int tipo { get; set; } // int(11)
        public int emisor { get; set; } // int

        // fk_folio_emisor
        [Association(ThisKey = "emisor", OtherKey = "idemisor", CanBeNull = false)]
        public emisor fkemisor { get; set; }
        // fk_folio_tipo
        [Association(ThisKey = "tipo", OtherKey = "id", CanBeNull = false)]
        public tipo fktipo { get; set; }
    }

    [TableName(Name = "producto")]
    public partial class producto
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int
        public string codigo { get; set; } // varchar(20)
        [Nullable]
        public string unidad_medida { get; set; } // varchar(20)
        public string descripcion { get; set; } // text
        public decimal valor_unitario { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? descuento { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? ieps { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? iva { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? ish { get; set; } // decimal(18,6)
        [Nullable]
        public decimal? isn { get; set; } // decimal(18,6)
        [Nullable]
        public string cuenta_predial { get; set; } // varchar(20)
        public int emisor { get; set; } // int

        // fk_factura_emisor
        [Association(ThisKey = "emisor", OtherKey = "idemisor", CanBeNull = false)]
        public receptor fkemisor { get; set; }
    }

    [TableName(Name = "moneda")]
    public partial class moneda
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int
        [Nullable]
        public string nombre { get; set; } // varchar(20)
        [Nullable]
        public decimal? tipo_cambio { get; set; } // varchar(20)
        [Nullable]
        public string abreviatura { get; set; } // varchar(20)
    }

    [TableName(Name = "pago")]
    public partial class pago
    {
        [Identity, PrimaryKey(1)]
        public string id { get; set; } // int - varchar(2) 22/06/2016
        [Nullable]
        public string metodo { get; set; } // varchar(50)
        [Nullable]
        public int? req_cuenta { get; set; } // varchar(20)
    }

    [TableName(Name = "tipo")]
    public partial class tipo
    {
        [Identity, PrimaryKey(1)]
        public int id { get; set; } // int
        [Nullable]
        public string tipo_comprobante { get; set; } // varchar(20)
        [Nullable]
        public string tipo_documento { get; set; } // varchar(20)

        // fk_ticket_tipo_BackReference
        [Association(ThisKey = "id", OtherKey = "tipo", CanBeNull = true)]
        public IEnumerable<folio> fkfolios { get; set; }
    }

    //Tablas agregadas para CFDI 3.3
    [TableName(Name = "cRegimenFiscal")]
    public partial class cRegimenFiscal
    {
        [PrimaryKey(1)]
        public Guid cRegimenFiscal_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(128)

        // fk_ticket_tipo_BackReference
        [Association(ThisKey = "cRegimenFiscal_id", OtherKey = "cRegimenFiscal_id", CanBeNull = true)]
        public IEnumerable<emisor> fkemisor { get; set; }
    }

    [TableName(Name = "cClaveProdServ")]
    public partial class cClaveProdServ
    {
        [PrimaryKey(1)]
        public string cClaveProdServ_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
        // fk_ticket_tipo_BackReference
        [Association(ThisKey = "cClaveProdServ_id", OtherKey = "cClaveProdServ_id", CanBeNull = true)]
        public IEnumerable<emisor_cProdServ> fkcProdServ_emisor { get; set; }
    }

    [TableName(Name = "cMetodoPago")]
    public partial class cMetodoPago
    {
        [PrimaryKey(1)]
        public string cMetodoPago_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "cFormaPago")]
    public partial class cFormaPago
    {
        [PrimaryKey(1)]
        public string cFormaPago_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "cUsoCFDI")]
    public partial class cUsoCFDI
    {
        [PrimaryKey(1)]
        public string cUsoCFDI_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "ctiporelacion")]
    public partial class cTipoRelacion
    {
        [PrimaryKey(1)]
        public string cTipoRelacion_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "cClaveUnidad")]
    public partial class cClaveUnidad
    {
        [PrimaryKey(1)]
        public string c_ClaveUnidad_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "cPais")]
    public partial class cPais
    {
        [PrimaryKey(1)]
        public string cPais_id { get; set; } // varchar(36)
        [Nullable]
        public string codigo { get; set; } // varchar(16)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "cTipoFactor")]
    public partial class cTipoFactor
    {
        [PrimaryKey(1)]
        public string cTipoFactor_id { get; set; } // varchar(36)
        [Nullable]
        public string descripcion { get; set; } // varchar(256)
    }

    [TableName(Name = "cTasaOCuota")]
    public partial class cTasaOCuota
    {
        [PrimaryKey(1)]
        public string cTasaOCuota_id { get; set; } // varchar(36)
        [Nullable]
        public string tasacuota { get; set; } // varchar(256)
    }

    [TableName(Name = "emisor_cProdServ")]
    public partial class emisor_cProdServ
    {
        [PrimaryKey(1)]
        public int emisor_id { get; set; } // varchar(16)
        [PrimaryKey(2)]
        public Guid cClaveProdServ_id { get; set; } // varchar(36)

        [Association(ThisKey = "emisor_id", OtherKey = "idemisor", CanBeNull = true)]
        public emisor fkemisor_cProdServ { get; set; }

        [Association(ThisKey = "cClaveProdServ_id", OtherKey = "cClaveProdServ_id", CanBeNull = true)]
        public cClaveProdServ fkcProdServ_emisor { get; set; }

    }

    //Seccion de declaracion de las tablas del CFDIRIP
    #region Instanciacion de las tablas del CFDIRIP
    [TableName(Name = "cfdirip")]
    public partial class cfdirip
    {
        [Identity, PrimaryKey(1)]
        public int idcfdirip { get; set; } // int(11)
        public int emisor { get; set; } // int(11)
        public int receptor { get; set; } // int(11) 
        [Nullable]
        public string foliointerno { get; set; } // varchar(20)
        public DateTime fechaexp { get; set; } // datetime
        public string clave { get; set; }// varchar(6)
        [Nullable]
        public string descripcion { get; set; } // varchar(100)
        public int mesinicial { get; set; } // int(2)
        public int mesfinal { get; set; } // int(2)
        public int ejerciciofiscal { get; set; } // int(4)
        public decimal montototoperacion { get; set; } // decimal(18,6)
        public decimal montototgrav { get; set; } // decimal(18,6)
        public decimal montototexent { get; set; } // decimal(18,6)
        public decimal montototret { get; set; } // decimal(18,6)
        [Nullable]
        public int? enajenaciondeacciones { get; set; }// int(11)
        [Nullable]
        public int? dividendos { get; set; }// int(11)
        [Nullable]
        public int? intereses { get; set; }// int(11)
        [Nullable]
        public int? arrendamientoenfideicomiso { get; set; }// int(11)
        [Nullable]
        public int? premios { get; set; }// int(11)
        [Nullable]
        public int? fideicnoempresarial { get; set; }// int(11)
        [Nullable]
        public int? planesderetiro { get; set; }// int(11)
        [Nullable]
        public int? intereseshipotecarios { get; set; }// int(11)
        [Nullable]
        public int? operacionesconderivados { get; set; }// int(11)
        [Nullable]
        public int? sectorfinanciero { get; set; }// int(11)
        [Nullable]
        public int? pagosaextranjeros { get; set; }// int(11)
        [Nullable]
        public string estatus { get; set; }// varchar(50)

        // fk_cfdirip_emisor
        [Association(ThisKey = "emisor", OtherKey = "idemisor", CanBeNull = false)]
        public emisor fkemisor { get; set; }

        // fk_cfdirip_receptor
        [Association(ThisKey = "receptor", OtherKey = "idreceptor", CanBeNull = false)]
        public receptor fkreceptor { get; set; }

        // fk_cfdirip_arrendamientoenfideicomiso
        [Association(ThisKey = "arrendamientoenfideicomiso", OtherKey = "idarrendamientoenfideicomiso", CanBeNull = false)]
        public arrendamientoenfideicomiso fkarrendamientoenfideicomiso { get; set; }

        // fk_cfdirip_dividendos
        [Association(ThisKey = "dividendos", OtherKey = "iddividendos", CanBeNull = false)]
        public dividendos fkdividendos { get; set; }

        // fk_cfdirip_enajenaciondeacciones
        [Association(ThisKey = "enajenaciondeacciones", OtherKey = "idenajenaciondeacciones", CanBeNull = false)]
        public enajenaciondeacciones fkenajenaciondeacciones { get; set; }

        // fk_cfdirip_fideicnoempresarial
        [Association(ThisKey = "fideicnoempresarial", OtherKey = "idfideicnoempresarial", CanBeNull = false)]
        public fideicnoempresarial fkfideicnoempresarial { get; set; }

        // fk_cfdirip_intereses
        [Association(ThisKey = "intereses", OtherKey = "idintereses", CanBeNull = false)]
        public intereses fkintereses { get; set; }

        // fk_cfdirip_intereseshipotecarios
        [Association(ThisKey = "intereseshipotecarios", OtherKey = "idintereseshipotecarios", CanBeNull = false)]
        public intereseshipotecarios fkintereseshipotecarios { get; set; }
        
        // fk_cfdirip_operacionesconderivados
        [Association(ThisKey = "operacionesconderivados", OtherKey = "idoperacionesconderivados", CanBeNull = false)]
        public operacionesconderivados fkoperacionesconderivados { get; set; }

        // fk_cfdirip_pagosaextranjeros
        [Association(ThisKey = "pagosaextranjeros", OtherKey = "idpagosaextranjeros", CanBeNull = false)]
        public pagosaextranjeros fkpagosaextranjeros { get; set; }

        // fk_cfdirip_planesderetiro
        [Association(ThisKey = "planesderetiro", OtherKey = "idplanesderetiro", CanBeNull = false)]
        public planesderetiro fkplanesderetiro { get; set; }

        // fk_cfdirip_premios
        [Association(ThisKey = "premios", OtherKey = "idpremios", CanBeNull = false)]
        public premios fkpremios { get; set; }

        // fk_cfdirip_sectorfinanciero
        [Association(ThisKey = "sectorfinanciero", OtherKey = "idsectorfinanciero", CanBeNull = false)]
        public sectorfinanciero fksectorfinanciero { get; set; }

        
        /////////////////
        // fk_facturacfdirip_cfdirip_BackReference
        [Association(ThisKey = "idcfdirip", OtherKey = "cfdirip", CanBeNull = true)]
        public IEnumerable<facturacfdirip> fkfacturascfdirip { get; set; }

        // fk_impuestosretenidos_cfdirip_BackReference
        [Association(ThisKey = "idcfdirip", OtherKey = "cfdirip", CanBeNull = true)]
        public IEnumerable<impuestosretenidos> fkimpuestosretenidos { get; set; }
    }

    [TableName(Name = "impuestosretenidos")]
    public partial class impuestosretenidos
    {
        [PrimaryKey(1)]
        public int idimpuestosretenidos { get; set; } // int(11)
        [Nullable]
        public decimal? baseimp { get; set; } // decimal(18,6)
        [Nullable]
        public string impuesto { get; set; }// varchar(6)
        public decimal monto { get; set; } // decimal(18, 6)
        public string tipopago { get; set; } // varchar(15)
        public int cfdirip { get; set; }// int(11)

        //fk_impuestosretenidos_cfdirip
        [Association(ThisKey = "cfdirip", OtherKey = "idcfdirip", CanBeNull = false)]
        public cfdirip fkcfdirip { get; set; }
    }

    [TableName(Name = "arrendamientoenfideicomiso")]
    public partial class arrendamientoenfideicomiso {
        [Identity, PrimaryKey(1)]
        public int idarrendamientoenfideicomiso { get; set; }// int(11)
        public decimal pagprovefecporfiduc { get; set;}// decimal(18,6)
        public decimal rendimfideicom { get; set; }// decimal(18,6)
        public decimal deducccorresp { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? monttotret { get; set; }// decimal(18,6) 
        [Nullable]
        public decimal? montresfiscdistfibras { get; set; }// decimal(18,6) 
        [Nullable]
        public decimal? montotrosconceptdistr { get; set; }// decimal(18,6) 
        public string descrmontotrosconceptdistr { get; set; }// varchar(300)

        // fk_arrendamientoenfideicomiso_cfdirip_BackReference
        [Association(ThisKey="idarrendamientoenfideicomiso", OtherKey="arrendamientoenfideicomiso", CanBeNull=false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }

    }

    [TableName(Name = "dividendos")]
    public partial class dividendos
    {
        [Identity, PrimaryKey(1)]
        public int iddividendos { get; set; }// int(11)
        public string cvetipdivoutil { get; set; }// varchar(6)
        public decimal montisracredretmexico { get; set; }// decimal(18,6)
        public decimal montisracredretextranjero { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? montretextdivext { get; set; }// decimal(18,6) 
        public string tiposocdistrdiv { get; set; }// varchar(18) 
        [Nullable]
        public decimal? montisracrednal { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? montdivacumnal { get; set; }// decimal(18,6) 
        [Nullable]
        public decimal? montdivacumext { get; set; }// decimal(18,6) 
        [Nullable]
        public decimal? proporcionrem { get; set; }// decimal(18,6) 

        // fk_dividendos_cfdirip_BackReference
        [Association(ThisKey = "iddividendos", OtherKey = "dividendos", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "enajenaciondeacciones")]
    public partial class enajenaciondeacciones
    {
        [Identity, PrimaryKey(1)]
        public int idenajenaciondeacciones { get; set; }// int(11)
        public string contratointermediacion { get; set; }// varchar(300)
        public decimal ganancia { get; set; }// decimal(18,6)
        public decimal perdida { get; set; }// decimal(18,6)

        // fk_enajenaciondeacciones_cfdirip_BackReference
        [Association(ThisKey = "idenajenaciondeacciones", OtherKey = "enajenaciondeacciones", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "fideicnoempresarial")]
    public partial class fideicnoempresarial
    {
        [Identity, PrimaryKey(1)]
        public int idfideicnoempresarial { get; set; }// int(11)
        public decimal monttotentradasperiodo { get; set; }// decimal(18,6)
        public decimal partpropacumdelfideicom { get; set; }// decimal(18,6)
        public decimal propdelmonttotingresosoentradas { get; set; }// decimal(18,6)
        public string concepto { get; set; }// varchar(100)
        public decimal monttotegresperiodo { get; set; }// decimal(18,6)
        public decimal partpropdelfideicom { get; set; }// decimal(18,6)
        public decimal propdelmonttotdeduccosalida { get; set; }// decimal(18,6)
        public string concepto_s { get; set; }// varchar(100)
        public decimal montretrelpagfideic { get; set; }// decimal(18,6)
        public string descretrelpagfideic { get; set; }// varchar(100)
        
        // fk_fideicnoempresarial_cfdirip_BackReference
        [Association(ThisKey = "idfideicnoempresarial", OtherKey = "fideicnoempresarial", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "intereses")]
    public partial class intereses
    {
        [Identity, PrimaryKey(1)]
        public int idintereses { get; set; }// int(11)
        public string sistemafinanciero { get; set; }// varchar(2)
        public string retiroaoresretint { get; set; }// varchar(2)
        public string operfinancderivad { get; set; }// varchar(2)
        public decimal montintnominal { get; set; }// decimal(18,6)
        public decimal montintreal { get; set; }// decimal(18,6)
        public decimal perdida { get; set; }// decimal(18,6)

        // fk_intereses_cfdirip_BackReference
        [Association(ThisKey = "idintereses", OtherKey = "intereses", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "intereseshipotecarios")]
    public partial class intereseshipotecarios
    {
        [Identity, PrimaryKey(1)]
        public int idintereseshipotecarios { get; set; }// int(11)
        public string creditodeInstfinanc { get; set; }// varchar(2)
        public decimal saldoinsoluto { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? propdeducdelcredit { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? monttotintnominalesdev { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? monttotintnominalesdevypag { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? monttotintrealpagdeduc { get; set; }// decimal(18,6)
        [Nullable]
        public string numcontrato { get; set; }// varchar(300)

        // fk_intereseshipotecarios_cfdirip_BackReference
        [Association(ThisKey = "idintereseshipotecarios", OtherKey = "intereseshipotecarios", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "operacionesconderivados")]
    public partial class operacionesconderivados
    {
        [Identity, PrimaryKey(1)]
        public int idoperacionesconderivados { get; set; }// int(11)
        public decimal montganacum { get; set; }// decimal(18,6)
        public decimal montperdded { get; set; }// decimal(18,6)

        // fk_operacionesconderivados_cfdirip_BackReference
        [Association(ThisKey = "idoperacionesconderivados", OtherKey = "operacionesconderivados", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "pagosaextranjeros")]
    public partial class pagosaextranjeros
    {
        [Identity, PrimaryKey(1)]
        public int idpagosaextranjeros { get; set; }// int(11)
        public string esbenefefectdelcobro { get; set; }// varchar(2)
        [Nullable]
        public string paisderesidparaefecfisc { get; set; }// varchar(3)
        [Nullable]
        public string rfc { get; set; }// varchar(13)
        [Nullable]
        public string curp { get; set; }// varchar(18)
        [Nullable]
        public string nomdenrazsocb { get; set; }// varchar(300)
        public string conceptopago { get; set; }// varchar(5)
        public string descripcionconcepto { get; set; }// varchar(255)
        
        // fk_pagosaextranjeros_cfdirip_BackReference
        [Association(ThisKey = "idpagosaextranjeros", OtherKey = "pagosaextranjeros", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "planesderetiro")]
    public partial class planesderetiro
    {
        [Identity, PrimaryKey(1)]
        public int idplanesderetiro { get; set; }// int(11)
        public string sistemafinanc { get; set; }// varchar(2)
        [Nullable]
        public decimal? monttotaportanioinmanterior { get; set; }// decimal(18,6)
        public decimal montintrealesdevengnniooinmant { get; set; }// decimal(18,6)
        public string huboretirosanioInmantper { get; set; }// varchar(2)
        [Nullable]
        public decimal? monttotretiradoanioinmantper { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? monttotexentretiradoanioinmant { get; set; }// decimal(18,6)
        [Nullable]
        public decimal? monttotexedenteanioinmant { get; set; }// decimal(18,6)
        public string huboretirosanioinmant { get; set; }// varchar(2)
        [Nullable]
        public decimal? monttotretiradoanioInmant { get; set; }// decimal(18,6)

        // fk_planesderetiro_cfdirip_BackReference
        [Association(ThisKey = "idplanesderetiro", OtherKey = "planesderetiro", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "premios")]
    public partial class premios
    {
        [Identity, PrimaryKey(1)]
        public int idpremios { get; set; }// int(11)
        public string entidadfederativa { get; set; }// varchar(6)
        public decimal monttotpago { get; set; }// decimal(18,6)
        public decimal monttotpagograv { get; set; }// decimal(18,6)
        public decimal monttotpagoexent { get; set; }// decimal(18,6)

        // fk_premios_cfdirip_BackReference
        [Association(ThisKey = "idpremios", OtherKey = "premios", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "sectorfinanciero")]
    public partial class sectorfinanciero
    {
        [Identity, PrimaryKey(1)]
        public int idsectorfinanciero { get; set; }// int(11)
        public string idfideicom { get; set; }// varchar(20)
        [Nullable]
        public string nomfideicom { get; set; }// varchar(100)
        public string descripfideicom { get; set; }// varchar(300)

        // fk_sectorfinanciero_cfdirip_BackReference
        [Association(ThisKey = "idsectorfinanciero", OtherKey = "sectorfinanciero", CanBeNull = false)]
        public IEnumerable<cfdirip> fkcfdirip { get; set; }
    }

    [TableName(Name = "catalogopaises")]
    public partial class catalogopaises
    {
        [PrimaryKey(1)]
        public string idcatalogopaises { get; set; }// varchar(3)
        public string pais { get; set; }// varchar(100)
    }

    [TableName(Name = "facturacfdirip")]
    public partial class facturacfdirip
    {
        [PrimaryKey(1)]
        public string uuid { get; set; } // char(36)
        public DateTime fecha_timbrado { get; set; } // datetime
        public int receptor { get; set; } // int(10)
        public int cfdirip { get; set; } // int(10)

        // fk_facturacfdirip_receptor
        [Association(ThisKey = "receptor", OtherKey = "idreceptor", CanBeNull = false)]
        public receptor fkreceptor { get; set; }

        // fk_facturacfdirip_cfdirip
        [Association(ThisKey = "cfdirip", OtherKey = "idcfdirip", CanBeNull = false)]
        public cfdirip fkcfdirip { get; set; }
    }
    #endregion
}
