//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/donat")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/donat", IsNullable = false)]
public partial class Donatarias
{

    private string versionField;

    private string noAutorizacionField;

    private System.DateTime fechaAutorizacionField;

    private string leyendaField;

    public Donatarias()
    {
        this.versionField = "1.1";
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noAutorizacion
    {
        get
        {
            return this.noAutorizacionField;
        }
        set
        {
            this.noAutorizacionField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
    public System.DateTime fechaAutorizacion
    {
        get
        {
            return this.fechaAutorizacionField;
        }
        set
        {
            this.fechaAutorizacionField = value;
        }
    }

    /// <comentarios/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string leyenda
    {
        get
        {
            return this.leyendaField;
        }
        set
        {
            this.leyendaField = value;
        }
    }
}
